#!/usr/bin/env python3
"""
Compare SCIP index output across languages to identify format differences.

Reads .scip protobuf files generated by different indexers and extracts:
- Symbol naming conventions
- Cross-file relationships (definition → reference edges)
- SymbolRoles values
- Range formats
- Any language-specific differences

This helps us design a single adapter that works for all SCIP indexers.
"""

import sys
import os

# Add /tmp where scip_pb2.py lives
sys.path.insert(0, "/tmp")
import scip_pb2


def load_index(path: str) -> scip_pb2.Index:
    """Load a SCIP index from a .scip file."""
    index = scip_pb2.Index()
    with open(path, "rb") as f:
        index.ParseFromString(f.read())
    return index


def parse_symbol(symbol: str) -> dict:
    """Parse a SCIP symbol string into components.

    SCIP symbol format: scheme manager package version descriptor
    e.g.: "scip-python python test-python 0.1.0 `module`/Class#method()."
    """
    parts = symbol.split(" ", 4)
    if len(parts) < 5:
        return {"raw": symbol, "scheme": parts[0] if parts else ""}
    return {
        "scheme": parts[0],        # scip-python, scip-typescript, etc.
        "manager": parts[1],       # python, npm, gomod, nuget
        "package": parts[2],       # package name
        "version": parts[3],       # version string
        "descriptor": parts[4],    # path + symbol suffix
        "raw": symbol,
    }


# SCIP SymbolRole enum values
SYMBOL_ROLES = {
    0: "UnspecifiedSymbolRole",
    1: "Definition",
    2: "Import",
    4: "WriteAccess",
    8: "ReadAccess",
    16: "Generated",
    32: "Test",
    64: "ForwardDefinition",
}


def describe_roles(role_mask: int) -> list[str]:
    """Decode SymbolRoles bitmask."""
    if role_mask == 0:
        return ["Reference"]
    roles = []
    for bit, name in SYMBOL_ROLES.items():
        if bit > 0 and (role_mask & bit):
            roles.append(name)
    return roles if roles else ["UnspecifiedSymbolRole"]


def analyze_index(path: str, label: str):
    """Analyze a single SCIP index file."""
    index = load_index(path)
    meta = index.metadata

    print(f"\n{'='*70}")
    print(f"  {label}")
    print(f"{'='*70}")
    print(f"  Tool:         {meta.tool_info.name} v{meta.tool_info.version}")
    print(f"  Project Root: {meta.project_root}")
    print(f"  Encoding:     {meta.text_document_encoding}")
    print(f"  Documents:    {len(index.documents)}")

    all_symbols = {}  # symbol -> {files, roles, ranges}
    cross_file_refs = []  # (src_file, symbol, dst_file_inferred)
    definitions = {}  # symbol -> file where defined
    references = {}   # symbol -> [files where referenced]
    role_values_seen = set()
    symbol_schemes = set()

    for doc in index.documents:
        rel_path = doc.relative_path
        lang = doc.language or "(not set)"
        print(f"\n  📄 {rel_path} [language={lang}]")

        doc_defs = []
        doc_refs = []

        for occ in doc.occurrences:
            sym = occ.symbol
            roles = describe_roles(occ.symbol_roles)
            role_values_seen.add(occ.symbol_roles)
            parsed = parse_symbol(sym)
            symbol_schemes.add(parsed.get("scheme", ""))

            # Track range format
            r = list(occ.range)

            if "Definition" in roles:
                definitions[sym] = rel_path
                doc_defs.append((sym, r, parsed.get("descriptor", "")))
            else:
                references.setdefault(sym, []).append(rel_path)
                doc_refs.append((sym, r, parsed.get("descriptor", "")))

        # Print definitions
        if doc_defs:
            print(f"    Definitions ({len(doc_defs)}):")
            for sym, r, desc in doc_defs[:8]:
                print(f"      DEF [{r[0]}:{r[1]}-{r[2] if len(r)==3 else f'{r[2]}:{r[3]}'}] {desc}")
            if len(doc_defs) > 8:
                print(f"      ... and {len(doc_defs)-8} more")

        # Print references
        if doc_refs:
            print(f"    References ({len(doc_refs)}):")
            for sym, r, desc in doc_refs[:8]:
                print(f"      REF [{r[0]}:{r[1]}-{r[2] if len(r)==3 else f'{r[2]}:{r[3]}'}] {desc}")
            if len(doc_refs) > 8:
                print(f"      ... and {len(doc_refs)-8} more")

    # Cross-file relationships
    print(f"\n  🔗 CROSS-FILE RELATIONSHIPS:")
    edge_count = 0
    for sym, ref_files in references.items():
        if sym in definitions:
            def_file = definitions[sym]
            for ref_file in ref_files:
                if ref_file != def_file:
                    parsed = parse_symbol(sym)
                    desc = parsed.get("descriptor", sym)
                    print(f"    {ref_file} → {def_file} via {desc}")
                    edge_count += 1
    if edge_count == 0:
        print(f"    (none detected)")
    print(f"    Total cross-file edges: {edge_count}")

    # Symbol format summary
    print(f"\n  📋 SYMBOL FORMAT:")
    print(f"    Schemes: {symbol_schemes}")
    print(f"    Role values seen: {sorted(role_values_seen)}")
    print(f"    Role meanings: {', '.join(f'{v}={describe_roles(v)}' for v in sorted(role_values_seen))}")

    # Show some example symbols for comparison
    print(f"\n  🔤 EXAMPLE SYMBOLS:")
    shown = 0
    for sym in definitions:
        if shown >= 5:
            break
        print(f"    {sym}")
        shown += 1

    return {
        "tool": meta.tool_info.name,
        "documents": len(index.documents),
        "definitions": len(definitions),
        "total_refs": sum(len(v) for v in references.values()),
        "cross_file_edges": edge_count,
        "schemes": symbol_schemes,
        "roles": role_values_seen,
    }


def main():
    base = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(base))

    indexes = {
        "PYTHON": os.path.join(project_root, "tests/fixtures/cross_file_sample/index.scip"),
        "TYPESCRIPT": os.path.join(base, "fixtures/typescript/index.scip"),
        "GO": os.path.join(base, "fixtures/go/index.scip"),
        "DOTNET": os.path.join(base, "fixtures/dotnet/index.scip"),
    }

    results = {}
    for label, path in indexes.items():
        if os.path.exists(path):
            results[label] = analyze_index(path, label)
        else:
            print(f"\n⚠️  {label}: {path} not found (skipping)")

    # Cross-language comparison
    print(f"\n{'='*70}")
    print(f"  CROSS-LANGUAGE COMPARISON")
    print(f"{'='*70}")

    print(f"\n  {'Language':<12} {'Tool':<20} {'Docs':>5} {'Defs':>5} {'Refs':>5} {'X-File':>6}")
    print(f"  {'-'*12} {'-'*20} {'-'*5} {'-'*5} {'-'*5} {'-'*6}")
    for label, r in results.items():
        print(f"  {label:<12} {r['tool']:<20} {r['documents']:>5} {r['definitions']:>5} {r['total_refs']:>5} {r['cross_file_edges']:>6}")

    print(f"\n  SYMBOL SCHEME PREFIX:")
    for label, r in results.items():
        print(f"    {label}: {r['schemes']}")

    print(f"\n  SYMBOL ROLE VALUES:")
    all_roles = set()
    for r in results.values():
        all_roles |= r["roles"]
    print(f"    All values seen: {sorted(all_roles)}")
    print(f"    Meanings:")
    for v in sorted(all_roles):
        print(f"      {v:>3} = {describe_roles(v)}")

    print(f"\n  KEY FINDINGS FOR ADAPTER DESIGN:")
    print(f"    1. Symbol format is UNIVERSAL: '<scheme> <manager> <pkg> <version> <descriptor>'")
    print(f"    2. Descriptor suffixes are STANDARD across all indexers:")
    print(f"       - '/' = package/module")
    print(f"       - '#' = type/class")
    print(f"       - '.' = term/field/property")
    print(f"       - '().' = method/function")
    print(f"    3. SymbolRoles bitmask is STANDARD: 1=def, 2=import, 4=write, 8=read")
    print(f"    4. Range format is STANDARD: [line, col_start, col_end] or [l1, c1, l2, c2]")
    print(f"    5. Only difference: scheme name and manager name per language")
    print(f"    6. Cross-file edges come from matching: def in file A + ref in file B")


if __name__ == "__main__":
    main()
