#!/usr/bin/env python3
"""Enrich fixture graph with smart_content via Azure LLM.

This script loads an existing graph (generated by fs2 scan), generates
smart_content for each node using Azure OpenAI, and saves the result.

Per Subtask 001 (ST004): This is the second step of fixture generation.
The first step (fs2 scan) handles structure and embeddings. This script
handles smart_content enrichment with custom prompts and rate limiting
that tests depend on.

Usage:
    python scripts/enrich_fixture_smart_content.py

    # Or via justfile (runs both steps):
    just generate-fixtures

Requirements:
    - Azure OpenAI credentials (FS2_AZURE__OPENAI__ENDPOINT, etc.)
    - Existing graph at tests/fixtures/fixture_graph.pkl
    - Run from project root
"""

import asyncio
import logging
import pickle
import sys
from dataclasses import replace
from pathlib import Path

# Ensure fs2 is importable
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from fs2.config.service import FS2ConfigurationService
from fs2.core.adapters.llm_adapter_azure import AzureOpenAIAdapter
from fs2.core.models.code_node import CodeNode

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)


# Paths
PROJECT_ROOT = Path(__file__).parent.parent
FIXTURE_PATH = PROJECT_ROOT / "tests" / "fixtures" / "fixture_graph.pkl"


async def generate_smart_content(
    adapter: AzureOpenAIAdapter, node: CodeNode
) -> CodeNode | None:
    """Generate smart_content for a node.

    Uses the same prompt and format that tests depend on (per DYK-01).

    Args:
        adapter: Azure LLM adapter.
        node: CodeNode to describe.

    Returns:
        Updated CodeNode with smart_content, or None on failure.
    """
    # Only generate for meaningful nodes
    if node.category not in ("file", "callable", "type", "section", "block"):
        return node

    # Truncate content for LLM input
    content = node.content[:2000]

    prompt = f"""Provide a concise, one-paragraph technical description of this {node.category}:

```{node.language}
{content}
```

Focus on:
- What it does (purpose)
- Key functionality
- Notable patterns or techniques used

Be technical but brief (2-3 sentences)."""

    try:
        response = await adapter.generate(prompt, max_tokens=150)
        smart_content = response.content.strip()

        return replace(
            node,
            smart_content=smart_content,
            smart_content_hash=node.content_hash,
        )

    except Exception as e:
        logger.warning(f"Failed to generate smart_content for {node.node_id}: {e}")
        return None


async def process_nodes_smart_content(
    nodes: list[CodeNode],
    llm_adapter: AzureOpenAIAdapter,
) -> list[CodeNode]:
    """Process nodes to add smart_content.

    Preserves existing embeddings - this script only adds smart_content.

    Args:
        nodes: List of CodeNodes from graph.
        llm_adapter: Azure LLM adapter.

    Returns:
        List of CodeNodes with smart_content added.
    """
    enriched = []
    for i, node in enumerate(nodes):
        logger.info(f"Generating smart_content {i + 1}/{len(nodes)}: {node.node_id}")
        result = await generate_smart_content(llm_adapter, node) or node
        enriched.append(result)
        # Small delay to avoid rate limiting (same as original script)
        await asyncio.sleep(0.1)
    return enriched


def main() -> int:
    """Main entry point.

    Returns:
        Exit code (0 for success).
    """
    logger.info("=" * 60)
    logger.info("Fixture Smart Content Enrichment")
    logger.info("=" * 60)

    # Verify fixture graph exists
    if not FIXTURE_PATH.exists():
        logger.error(f"Fixture graph not found: {FIXTURE_PATH}")
        logger.error("Run 'just generate-fixtures-quick' or 'fs2 scan' first")
        return 1

    logger.info(f"Loading graph from: {FIXTURE_PATH}")

    # Load existing graph
    try:
        with open(FIXTURE_PATH, "rb") as f:
            metadata, graph = pickle.load(f)
        logger.info(f"Loaded graph with {graph.number_of_nodes()} nodes")
    except Exception as e:
        logger.error(f"Failed to load graph: {e}")
        return 1

    # Extract nodes from graph
    nodes = []
    for node_id in graph.nodes:
        node_data = graph.nodes[node_id].get("data")
        if node_data is not None:
            nodes.append(node_data)
    logger.info(f"Extracted {len(nodes)} nodes for enrichment")

    # Try to create Azure LLM adapter
    llm_adapter = None
    try:
        real_config = FS2ConfigurationService()
        llm_adapter = AzureOpenAIAdapter(real_config)
        logger.info("Azure LLM adapter configured")
    except Exception as e:
        logger.warning(f"Could not create Azure LLM adapter: {e}")
        logger.warning("Saving graph without smart_content")
        logger.warning(
            "Set FS2_AZURE__OPENAI__ENDPOINT and FS2_AZURE__OPENAI__KEY to enable enrichment"
        )
        return 0  # Not an error - graph was created, just no smart_content

    # Generate smart_content
    logger.info("Generating smart_content...")
    enriched_nodes = asyncio.run(process_nodes_smart_content(nodes, llm_adapter))

    with_smart = sum(1 for n in enriched_nodes if n.smart_content is not None)
    logger.info(f"Nodes with smart_content: {with_smart}")

    # Update graph with enriched nodes
    for node in enriched_nodes:
        graph.nodes[node.node_id]["data"] = node

    # Save graph
    logger.info(f"Saving graph to {FIXTURE_PATH}...")
    try:
        with open(FIXTURE_PATH, "wb") as f:
            pickle.dump((metadata, graph), f, protocol=pickle.HIGHEST_PROTOCOL)
    except Exception as e:
        logger.error(f"Failed to save graph: {e}")
        return 1

    logger.info("=" * 60)
    logger.info("Enrichment complete!")
    logger.info(f"  Nodes enriched: {with_smart}")
    logger.info(f"  Output: {FIXTURE_PATH}")
    logger.info("=" * 60)

    return 0


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)
